<?php
return [
    'adminEmail' => 'admin@example.com',
    'baseUrl' => '',
    'htmlUrl' => '/html',
    'SMS_SN' => 'DXX-WSS-100-10994',
    'SMS_SIG' => '申友国际教育',
    'SMS_PWD' => '057499',
    'timeLimit' => 600,
    'defaultImg' => '',
    'emailTimeLimit' => 24 * 3600,
    'phone1' => '您正在通过手机免费注册申友论坛！',
//    'phone2' => '您正在通过手机预约申友网留学顾问！',
//    'phone3' => '您正在通过手机预约申友网考试培训顾问！',
//    'phone4' => '您正在通过手机免费注册申友网公开课会员！',
//    'phone5' => '您正在通过手机找回申友公开课账号密码！',
//    'phone6' => '您正在通过邮箱免费注册申友网公开课会员！',
//    'phone7' => '您正在通过邮箱找回申友公开课账号密码！',
//    'phone8' => '您正在修改绑定手机！',
//    'phone9' => '您正在修改绑定邮箱！',
//    'schoolUrl' => 'http://schools.smartapply.cn/cn/api/school',
//    'categoryUrl' => 'http://schools.smartapply.cn/cn/api/cats',
//    'contentUrl' => 'http://schools.smartapply.cn/cn/api/content',
//    'schoolConnect' => 'http://schools.smartapply.cn',

    'report' => [
        1 => '垃圾营销',
        2 => '淫秽色情',
        3 => '有害信息',
        4 => '人身攻击',
        5 => '违法信息',
        6 => '用户建议',
        7 => '用户留言',
        8 => '用户预约',
    ],

    'levelName' => [
        0 => '回炉重造',
        1 => '见习会员',
        2 => '小有名气',
        3 => '知名人士',
        4 => '见习写手',
        5 => '正式写手',
        6 => '著名写手',
        7 => '见习作家',
        8 => '职业作家',
        9 => '知名作家',
        10 => '见习点评',
        11 => '论坛点评',
        12 => '著名点评',
        13 => '论坛精英',
        14 => '论坛支柱',
        15 => '论坛元老',
        16 => '坛圣',

    ]
];
